[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning:tensorboard[.*]"]

[tool.poetry]
name = "pyabc"
version = "0.0.0"
description = "Python Awesome Basic Calculus (PDE solver)"
authors = ["Kyoungseoun Chung <kchung@student.ethz.ch>"]

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.6.1"
pyevtk = "^1.5.0"
rich = "^12.6.0"
tensorboard = "^2.10.1"
torch = "^1.12.1"
numpy = "^1.23.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
